INSERT INTO MemberAudienceType (memberId, audienceType) VALUES
(1, 'Adults'),
(2, 'Adults'),
(3, 'Teens'),
(4, 'Teens'),
(5, 'Adults'),
(6, 'Seniors'),
(7, 'Students'),
(8, 'Researchers'),
(9, 'Writers'),
(10, 'Book Enthusiasts'),
(11, 'Film Lovers'),
(12, 'Science Enthusiasts'),
(13, 'Tech Enthusiasts'),
(14, 'History Buffs'),
(15, 'Philosophy Lovers');
